# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53d2f4067d3bf925b70211c18e6e2859c4ddea5f227b7569b77c8d263f965effdfec5cf8ea63d34cba714f2d1d4129c40f67c33f5a47d040737020bcf5e2ca77

test:
  secret_key_base: 10b2dee060ca9e353ea29fa430add921fad05d88a0f9464025f0567b125bb16158ddaee49228c87420636912c65d7dab5bb30d25eef45ce063eae58a9c6595f1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
